
services:
  driver-service:
    build: .
    ports:
      - "4343:4343"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@driver-db:5432/driver_service
      - NODE_ENV=production
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      driver-db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    networks:
      - shared-network

  driver-db:
    image: postgres:13
    ports:
      - "5434:5432"  
    environment:
      - POSTGRES_DB=driver_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - driver_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - shared-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5675:5672"  
      - "15675:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - shared-network

volumes:
  driver_db_data:

networks:
  shared-network:
