# Generated by Django 5.1.4 on 2024-12-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='estimated_fare',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
