# Generated by Django 5.0.1 on 2025-01-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='ride_request',
        ),
        migrations.AddField(
            model_name='booking',
            name='driver_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='ride_request_id',
            field=models.IntegerField(default=0),
        ),
    ]
